FROM golang:1.20.1-alpine AS builder

RUN apk add --no-cache git build-base

WORKDIR /go/src/github.com/aptible/mini-collector/

ADD go.mod .
ADD go.sum .
RUN go mod download

COPY . .
RUN go build github.com/aptible/mini-collector/cmd/mini-collector
RUN go build github.com/aptible/mini-collector/cmd/aggregator

FROM alpine:3.7
RUN apk add --no-cache ca-certificates
COPY --from=builder /go/src/github.com/aptible/mini-collector/<%= ENV.fetch('BINARY_NAME') %> /usr/local/bin/
EXPOSE 8000
CMD ["<%= ENV.fetch('BINARY_NAME') %>"]
