// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package _

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// NOTE: Protocol buffers used variable-length encoding, so even though uint64
// is arguably much bigger than we'd need, it's simpler to just use that. We
// do, however, use signed ints for disk usage and limit because those fields
// are optional (and should not be reported if they are < 0).
type PublishRequest struct {
	UnixTime             int64    `protobuf:"varint,1,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	Running              bool     `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	MilliCpuUsage        uint64   `protobuf:"varint,3,opt,name=milli_cpu_usage,json=milliCpuUsage,proto3" json:"milli_cpu_usage,omitempty"`
	MemoryTotalMb        uint64   `protobuf:"varint,4,opt,name=memory_total_mb,json=memoryTotalMb,proto3" json:"memory_total_mb,omitempty"`
	MemoryRssMb          uint64   `protobuf:"varint,5,opt,name=memory_rss_mb,json=memoryRssMb,proto3" json:"memory_rss_mb,omitempty"`
	MemoryLimitMb        uint64   `protobuf:"varint,6,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"`
	DiskUsageMb          int64    `protobuf:"zigzag64,7,opt,name=disk_usage_mb,json=diskUsageMb,proto3" json:"disk_usage_mb,omitempty"`
	DiskLimitMb          int64    `protobuf:"zigzag64,8,opt,name=disk_limit_mb,json=diskLimitMb,proto3" json:"disk_limit_mb,omitempty"`
	DiskReadKbps         uint64   `protobuf:"varint,9,opt,name=disk_read_kbps,json=diskReadKbps,proto3" json:"disk_read_kbps,omitempty"`
	DiskWriteKbps        uint64   `protobuf:"varint,10,opt,name=disk_write_kbps,json=diskWriteKbps,proto3" json:"disk_write_kbps,omitempty"`
	DiskReadIops         uint64   `protobuf:"varint,11,opt,name=disk_read_iops,json=diskReadIops,proto3" json:"disk_read_iops,omitempty"`
	DiskWriteIops        uint64   `protobuf:"varint,12,opt,name=disk_write_iops,json=diskWriteIops,proto3" json:"disk_write_iops,omitempty"`
	PidsCurrent          uint64   `protobuf:"varint,13,opt,name=pids_current,json=pidsCurrent,proto3" json:"pids_current,omitempty"`
	PidsLimit            uint64   `protobuf:"varint,14,opt,name=pids_limit,json=pidsLimit,proto3" json:"pids_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishRequest) Reset()         { *m = PublishRequest{} }
func (m *PublishRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()    {}
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *PublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRequest.Unmarshal(m, b)
}
func (m *PublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRequest.Marshal(b, m, deterministic)
}
func (m *PublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRequest.Merge(m, src)
}
func (m *PublishRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRequest.Size(m)
}
func (m *PublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRequest proto.InternalMessageInfo

func (m *PublishRequest) GetUnixTime() int64 {
	if m != nil {
		return m.UnixTime
	}
	return 0
}

func (m *PublishRequest) GetRunning() bool {
	if m != nil {
		return m.Running
	}
	return false
}

func (m *PublishRequest) GetMilliCpuUsage() uint64 {
	if m != nil {
		return m.MilliCpuUsage
	}
	return 0
}

func (m *PublishRequest) GetMemoryTotalMb() uint64 {
	if m != nil {
		return m.MemoryTotalMb
	}
	return 0
}

func (m *PublishRequest) GetMemoryRssMb() uint64 {
	if m != nil {
		return m.MemoryRssMb
	}
	return 0
}

func (m *PublishRequest) GetMemoryLimitMb() uint64 {
	if m != nil {
		return m.MemoryLimitMb
	}
	return 0
}

func (m *PublishRequest) GetDiskUsageMb() int64 {
	if m != nil {
		return m.DiskUsageMb
	}
	return 0
}

func (m *PublishRequest) GetDiskLimitMb() int64 {
	if m != nil {
		return m.DiskLimitMb
	}
	return 0
}

func (m *PublishRequest) GetDiskReadKbps() uint64 {
	if m != nil {
		return m.DiskReadKbps
	}
	return 0
}

func (m *PublishRequest) GetDiskWriteKbps() uint64 {
	if m != nil {
		return m.DiskWriteKbps
	}
	return 0
}

func (m *PublishRequest) GetDiskReadIops() uint64 {
	if m != nil {
		return m.DiskReadIops
	}
	return 0
}

func (m *PublishRequest) GetDiskWriteIops() uint64 {
	if m != nil {
		return m.DiskWriteIops
	}
	return 0
}

func (m *PublishRequest) GetPidsCurrent() uint64 {
	if m != nil {
		return m.PidsCurrent
	}
	return 0
}

func (m *PublishRequest) GetPidsLimit() uint64 {
	if m != nil {
		return m.PidsLimit
	}
	return 0
}

type PublishResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishResponse) Reset()         { *m = PublishResponse{} }
func (m *PublishResponse) String() string { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()    {}
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *PublishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResponse.Unmarshal(m, b)
}
func (m *PublishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResponse.Marshal(b, m, deterministic)
}
func (m *PublishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResponse.Merge(m, src)
}
func (m *PublishResponse) XXX_Size() int {
	return xxx_messageInfo_PublishResponse.Size(m)
}
func (m *PublishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PublishRequest)(nil), "PublishRequest")
	proto.RegisterType((*PublishResponse)(nil), "PublishResponse")
}

func init() {
	proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c)
}

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0x40, 0xab, 0xda, 0xb5, 0xad, 0xf1, 0x57, 0xbb, 0xa7, 0xa5, 0xa5, 0xa0, 0x8a, 0x52, 0x74,
	0xd2, 0xa1, 0xb9, 0xe6, 0x92, 0xf8, 0x14, 0x12, 0x43, 0x10, 0x0e, 0x81, 0x5c, 0x16, 0xc9, 0x5a,
	0x94, 0xc5, 0x92, 0x76, 0xb3, 0x1f, 0x24, 0xf9, 0x09, 0xf9, 0xd7, 0x61, 0x47, 0xb6, 0x63, 0x3b,
	0x47, 0x3d, 0x9e, 0x9e, 0x66, 0xc4, 0x40, 0x98, 0x2b, 0x91, 0x2a, 0x2d, 0xad, 0x8c, 0xdf, 0xfa,
	0x30, 0xbb, 0x75, 0x45, 0x2d, 0xcc, 0x63, 0xc6, 0x9f, 0x1c, 0x37, 0x96, 0xfc, 0x82, 0xd0, 0xb5,
	0xe2, 0x85, 0x59, 0xd1, 0x70, 0x1a, 0x44, 0x41, 0xd2, 0xcb, 0x46, 0x1e, 0xac, 0x44, 0xc3, 0x09,
	0x85, 0xa1, 0x76, 0x6d, 0x2b, 0xda, 0x8a, 0x7e, 0x8d, 0x82, 0x64, 0x94, 0xed, 0x1e, 0xc9, 0x3f,
	0x98, 0x37, 0xa2, 0xae, 0x05, 0x5b, 0x2b, 0xc7, 0x9c, 0xc9, 0x2b, 0x4e, 0x7b, 0x51, 0x90, 0xf4,
	0xb3, 0x29, 0xe2, 0x85, 0x72, 0x77, 0x1e, 0xa2, 0xc7, 0x1b, 0xa9, 0x5f, 0x99, 0x95, 0x36, 0xaf,
	0x59, 0x53, 0xd0, 0xfe, 0xd6, 0x43, 0xbc, 0xf2, 0x74, 0x59, 0x90, 0x18, 0xb6, 0x80, 0x69, 0x63,
	0xbc, 0xf5, 0x0d, 0xad, 0x71, 0x07, 0x33, 0x63, 0x96, 0xc5, 0x41, 0xab, 0x16, 0x8d, 0xb0, 0xde,
	0x1a, 0x1c, 0xb6, 0x6e, 0x3c, 0xed, 0x5a, 0xa5, 0x30, 0x9b, 0x6e, 0x2c, 0x6f, 0x0d, 0xa3, 0x20,
	0x21, 0xd9, 0xd8, 0x43, 0x9c, 0xea, 0xc0, 0xd9, 0x97, 0x46, 0x1f, 0xce, 0xae, 0xf3, 0x17, 0x66,
	0xe8, 0x68, 0x9e, 0x97, 0x6c, 0x53, 0x28, 0x43, 0x43, 0xfc, 0xdc, 0xc4, 0xd3, 0x8c, 0xe7, 0xe5,
	0x75, 0xa1, 0x8c, 0x9f, 0x0a, 0xad, 0x67, 0x2d, 0x2c, 0xef, 0x34, 0xe8, 0xa6, 0xf2, 0xf8, 0xde,
	0x53, 0xf4, 0x8e, 0x6a, 0x42, 0x2a, 0x43, 0xc7, 0xc7, 0xb5, 0x2b, 0xf9, 0xa9, 0x86, 0xda, 0xe4,
	0xa4, 0x86, 0xde, 0x1f, 0x98, 0x28, 0x51, 0x1a, 0xb6, 0x76, 0x5a, 0xf3, 0xd6, 0xd2, 0x69, 0xf7,
	0xbb, 0x3c, 0x5b, 0x74, 0x88, 0xfc, 0x06, 0x40, 0x05, 0x57, 0xa4, 0x33, 0x14, 0x42, 0x4f, 0x70,
	0xbf, 0xf8, 0x07, 0xcc, 0xf7, 0xa7, 0x60, 0x94, 0x6c, 0x0d, 0xff, 0x7f, 0x0e, 0x70, 0x51, 0x55,
	0x9a, 0x57, 0xb9, 0x95, 0x9a, 0xa4, 0x30, 0xdc, 0x0a, 0x64, 0x9e, 0x1e, 0x5f, 0xcd, 0xcf, 0xef,
	0xe9, 0xc9, 0xbb, 0xf1, 0x97, 0xcb, 0xde, 0x43, 0x90, 0x16, 0x03, 0x3c, 0xb4, 0xb3, 0xf7, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xf6, 0x92, 0xa8, 0x2a, 0x75, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AggregatorClient is the client API for Aggregator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AggregatorClient interface {
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
}

type aggregatorClient struct {
	cc grpc.ClientConnInterface
}

func NewAggregatorClient(cc grpc.ClientConnInterface) AggregatorClient {
	return &aggregatorClient{cc}
}

func (c *aggregatorClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, "/Aggregator/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggregatorServer is the server API for Aggregator service.
type AggregatorServer interface {
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
}

// UnimplementedAggregatorServer can be embedded to have forward compatible implementations.
type UnimplementedAggregatorServer struct {
}

func (*UnimplementedAggregatorServer) Publish(ctx context.Context, req *PublishRequest) (*PublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}

func RegisterAggregatorServer(s *grpc.Server, srv AggregatorServer) {
	s.RegisterService(&_Aggregator_serviceDesc, srv)
}

func _Aggregator_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregatorServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aggregator/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregatorServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Aggregator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Aggregator",
	HandlerType: (*AggregatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _Aggregator_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
